<pre>
    <?
    //print("_server\n");
    //print_r($_SERVER);
    print("_globals\n");
    print_r($GLOBALS);
    //print("_session\n");
    //print_r($_SESSION);
    //print("_cookie\n");
    //print_r($_COOKIE);
    //print("_get\n");
    //print_r($_GET);
    //print("_post\n");
    //print_r($_POST);
    //print("_request\n");
    //print_r($_REQUEST);//
    
    ?>
</pre>